Repository Manuelentrena/devathon-9-backend, pull requests merged in 2025-04, with the labels that each got.

#2 Feature/socket register user
  .gitignore
  griffindor-backend/pom.xml
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/GriffindorBackendApplication.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/Queues/PlayersConnectedQueue.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/Queues/PlayersListQueue.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/config/WebSocketConfig.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/config/WebSocketRoutes.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/GameSessionController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/PlayersOnlineController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/ErrorResponseDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/PlayerConnectedDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/PlayerCountDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/PlayerRegisterDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/SucessResponseDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/TokenIdResponseDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/enums/PlayerSessionState.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/events/PlayerCountUpdateEvent.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/events/PlayersConnectedEvent.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/events/PlayersListEvent.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/hooks/EventListenersLoggingHook.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/hooks/MessageMappingLoggingHook.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/listeners/PlayerCountUpdateListener.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/listeners/PlayersConnectedListener.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/listeners/PlayersListListener.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/middleware/CustomHandshakeMiddleware.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/models/Player.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/ErrorService.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/ErrorServiceImpl.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/PlayerServiceImpl.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/PlayerService.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/utils/Jwt.java
  griffindor-backend/src/main/resources/static/magic-hat/index.html
  griffindor-backend/src/main/resources/static/magic-hat/script.js
  griffindor-backend/src/main/resources/static/magic-hat/styles.css
Labels: enhancement

#4 Feature/socket join room
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/Queues/RoomReadyQueue.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/Queues/WaitlistQueue.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/config/SchedulerConfig.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/config/WebSocketRoutes.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/AssignRoomController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/GameSessionController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/PlayersOnlineController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/PlayerRegisterDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/RoomIdResponseDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/enums/RoomVisibility.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/events/RoomReadyEvent.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/listeners/RoomReadyListener.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/models/Room.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/PlayerServiceImpl.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/RoomServiceImpl.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/PlayerService.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/RoomService.java
Labels: enhancement

#6 Feature/springwolf dto
  griffindor-backend/pom.xml
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/GameSessionController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/PlayersOnlineController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/SpellResponseDto.java
Labels: bug

#12 Fix/app duel
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/controllers/AssignRoomController.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/dtos/RoomReadyResponseDto.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/events/RoomReadyEvent.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/listeners/RoomReadyListener.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/models/Room.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/PlayerServiceImpl.java
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/PlayerService.java
Labels: bug, enhancement

#13 fix(bug): :bug: Fixed resolveRound method
  griffindor-backend/src/main/java/com/devathon/griffindor_backend/services/Impl/SpellServiceImpl.java
Labels: bug
